version: '3.9'
services:
  notebook:
    container_name: datascience
    image: jupyter/datascience-notebook
    ports:
      - '8000:8000'
    environment:
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - /Users/tanakatouma/vscode/data-science/:/home/datascience/
    command: start-notebook.sh --NotebookApp.token=''