version: "3.9"
services:
  jupyterlab:
    build:
      context: ./jupyterlab
      dockerfile: Dockerfile
    container_name: ds_wiki_jupyterlab
    restart: always
    entrypoint: >
      jupyter-lab
      --allow-root
      --ip=0.0.0.0
      --port=8000
      --no-browser
      --NotebookApp.token=''
      --notebook-dir=/workspace
    expose:
      - "8000"
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - /Users/tanakatouma/Documents/Docker_volumes/data_science/root_jupyter:/root/.jupyter
      - /Users/tanakatouma/Documents/Docker_volumes/data_science/workspace:/workspace
  

    # GPUを使う場合の設定
    # environment:
    #   - "NVIDIA_VISIBLE_DEVICES=all"
    #   - "NVIDIA_DRIVER_CAPABILITIES=all"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - capabilities:
    #           - gpu